In [3]:
import zipfile, gc, os
import numpy as np
from modules import (
    MusicDataLoaderPl,
    NonePersonalizedRecommender,
    ContentBasedRecommender,
    CollaborativeFilteringRecommender
    )

# connecting google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Loading the dataset

I'm using a custom Million Song Dataset: https://yadi.sk/d/AJ2yfSnhcFTLjQ?w=1
And since I'm not running it locally, I uploaded the dataset on my google drive, home_path is the path to the dataset wheteer it's in the drive or in local

In [4]:
home_path = "drive/MyDrive/ds3/src/datasets/"
if len(os.listdir(home_path)) == 0:
  with zipfile.ZipFile(home_path+"p02_mxm_dataset_train.txt.zip") as zip_ref:
      zip_ref.extractall(home_path)
  with zipfile.ZipFile(home_path+"p02_train_triplets.txt.zip") as zip_ref:
      zip_ref.extractall(home_path)
os.listdir(home_path)

['p02_msd_tagtraum_cd2.cls',
 'p02_mxm_dataset_train.txt.zip',
 'p02_train_triplets.txt.zip',
 'p02_unique_tracks.txt',
 'extr',
 'mxm_dataset_train.txt',
 'train_triplets.txt',
 '__MACOSX']

Datasets to use:<br>
- p02_msd_tagtraum_cd2.cls<br>
- p02_unique_tracks.txt<br>
- train_triplets.txt
<h3>We are not using musiXmatch dataset! Bacuse there's something wrong with it and it's always filling up our non-existent precious RAM!</h3>

In [5]:
loader = MusicDataLoaderPl(
    triplets_path=home_path+"train_triplets.txt",
    unique_tracks_path=home_path+"p02_unique_tracks.txt",
    genres_path=home_path+"p02_msd_tagtraum_cd2.cls",
    sample_fraction=0.5)
df, tracks_df, triplets_df, genres_df = loader.load_data()

1. Loading unique tracks dataset...
2. Loading triplets dataset...
   Sampling 50.0% of triplets dataset...
3. Loading genres dataset...
4. Merging datasets...

In [6]:
print(df.shape)
df.head(5)

(24831952, 8)

shape: (5, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ user_id    ┆ song_id    ┆ play_count ┆ track_id  ┆ artist    ┆ title     ┆ majority- ┆ minorillt │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ genre     ┆ y-genre   │
│ cat        ┆ cat        ┆ i32        ┆ cat       ┆ str       ┆ str       ┆ ---       ┆ ---       │
│            ┆            ┆            ┆           ┆           ┆           ┆ str       ┆ str       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ ac3f9932eb ┆ SOVGSEL12A ┆ 1          ┆ TRBJRQN12 ┆ Lifehouse ┆ Blind     ┆ Rock      ┆ null      │
│ 88f33c7aa7 ┆ 8C141591   ┆            ┆ 8F4298744 ┆           ┆           ┆           ┆           │
│ 8bbba45183 ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ cc3026269e ┆ SOWMGYB12A ┆ 1          ┆ TRNCAZY12 ┆ Christoph ┆ Black     ┆ Rock      ┆ Jazz      │
│ 817841fa70 ┆ 8C136507   ┆            ┆ 8F4272748 ┆ er        ┆ Star      ┆           ┆           │
│ a63d7895f0 ┆            ┆            ┆           ┆ O'Riley   ┆           ┆           ┆           │
│ …          ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ db226f9e76 ┆ SOCDMKB12A ┆ 1          ┆ TRUOISO12 ┆ Mor W.A.  ┆ Co Nas    ┆ null      ┆ null      │
│ aa906f3dc8 ┆ 8C1344F5   ┆            ┆ 8F425623D ┆           ┆ Motywuje  ┆           ┆           │
│ dbebcce326 ┆            ┆            ┆           ┆           ┆ (Remix)   ┆           ┆           │
│ …          ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ 89cf0e4c3b ┆ SOOGWEB12A ┆ 1          ┆ TRPLMXP12 ┆ Rob       ┆ House Of  ┆ null      ┆ null      │
│ 3d6a140f14 ┆ 67020B58   ┆            ┆ 8E0792700 ┆ Zombie    ┆ 1000      ┆           ┆           │
│ 27b946096e ┆            ┆            ┆           ┆           ┆ Corpses   ┆           ┆           │
│ …          ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ e52dc967e2 ┆ SODRHMF12A ┆ 1          ┆ TRIHDCP12 ┆ Saeed     ┆ Backroom  ┆ null      ┆ null      │
│ ae87165f58 ┆ B0189504   ┆            ┆ 903CB30B4 ┆ Younan    ┆ Honey     ┆           ┆           │
│ 50418ce89b ┆            ┆            ┆           ┆           ┆ (Original ┆           ┆           │
│ …          ┆            ┆            ┆           ┆           ┆ Mix)      ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

# Modeling


## Top 250 Tracks | Top 100 tracks by genre

In [7]:
npr = NonePersonalizedRecommender(df)
genre = "Metal"

print("Top 250 songs:")
npr.get_top_250()

Top 250 songs:

shape: (250, 4)
┌──────────────┬─────────────────────────────────┬─────────────────────────────────┬────────────┐
│ index_number ┆ artist                          ┆ title                           ┆ play_count │
│ ---          ┆ ---                             ┆ ---                             ┆ ---        │
│ u32          ┆ str                             ┆ str                             ┆ i32        │
╞══════════════╪═════════════════════════════════╪═════════════════════════════════╪════════════╡
│ 1            ┆ Dwight Yoakam                   ┆ You're The One                  ┆ 362737     │
│ 2            ┆ Björk                           ┆ Undo                            ┆ 326957     │
│ 3            ┆ Kings Of Leon                   ┆ Revelry                         ┆ 263405     │
│ 4            ┆ Harmonia                        ┆ Sehr kosmisch                   ┆ 213049     │
│ 5            ┆ Barry Tuckwell/Academy of St M… ┆ Horn Concerto No. 4 in E flat … ┆ 195926     │
│ …            ┆ …                               ┆ …                               ┆ …          │
│ 246          ┆ Lady GaGa                       ┆ Monster                         ┆ 18685      │
│ 247          ┆ Kings Of Leon                   ┆ Be Somebody                     ┆ 18674      │
│ 248          ┆ Metallica / Marianne Faithfull  ┆ The Memory Remains              ┆ 18537      │
│ 249          ┆ Shaggy / Samantha Cole          ┆ Luv Me_ Luv Me                  ┆ 18410      │
│ 250          ┆ Cliff Richard & The Shadows     ┆ Nine Times Out Of Ten (1998 Di… ┆ 18378      │
└──────────────┴─────────────────────────────────┴─────────────────────────────────┴────────────┘

In [8]:
genre = "Jazz"
print(f'Top 100 tracks by "{genre}" genre:')
print(npr.get_top_100_by_genre(genre))

Top 100 tracks by "Jazz" genre:
shape: (100, 4)
┌──────────────┬───────────────────────────┬────────────────────────────┬────────────┐
│ index_number ┆ artist                    ┆ title                      ┆ play_count │
│ ---          ┆ ---                       ┆ ---                        ┆ ---        │
│ u32          ┆ str                       ┆ str                        ┆ i32        │
╞══════════════╪═══════════════════════════╪════════════════════════════╪════════════╡
│ 1            ┆ Ron Carter                ┆ I CAN'T GET STARTED        ┆ 80820      │
│ 2            ┆ Jacky Terrasson           ┆ Le Jardin d'Hiver          ┆ 37264      │
│ 3            ┆ Erin Bode                 ┆ Here_ There And Everywhere ┆ 22697      │
│ 4            ┆ Michael Bublé             ┆ Home (Album Version)       ┆ 13509      │
│ 5            ┆ Bohren & Der Club Of Gore ┆ Welk                       ┆ 12162      │
│ …            ┆ …                         ┆ …                          ┆ …          │
│ 96           ┆ Koop                      ┆ Tonight                    ┆ 1121       │
│ 97           ┆ Spyro Gyra                ┆ Morning Dance              ┆ 1103       │
│ 98           ┆ Jamie Cullum              ┆ London Skies               ┆ 1092       │
│ 99           ┆ Gonzalo Rubalcaba         ┆ Hot House                  ┆ 1091       │
│ 100          ┆ Jamie Cullum              ┆ Mind Trick                 ┆ 1090       │
└──────────────┴───────────────────────────┴────────────────────────────┴────────────┘

## Collections

In [9]:
keywords = ["love", "war"]
for keyword in keywords:
  print(f'50 Most played songs with "{keyword}" in the title:')
  cbr = ContentBasedRecommender(tracks_df, triplets_df)
  print(cbr.get_collection(keyword))

50 Most played songs with "love" in the title:
shape: (50, 4)
┌──────────────┬────────────────────────┬─────────────────────────────────┬────────────┐
│ index_number ┆ artist                 ┆ title                           ┆ play_count │
│ ---          ┆ ---                    ┆ ---                             ┆ ---        │
│ u32          ┆ str                    ┆ str                             ┆ i32        │
╞══════════════╪════════════════════════╪═════════════════════════════════╪════════════╡
│ 1            ┆ Bill Withers           ┆ Make Love To Your Mind          ┆ 72122      │
│ 2            ┆ Justin Bieber          ┆ Somebody To Love                ┆ 55448      │
│ 3            ┆ Justin Bieber          ┆ Somebody To Love                ┆ 55448      │
│ 4            ┆ Florence + The Machine ┆ Cosmic Love                     ┆ 47677      │
│ 5            ┆ Taylor Swift           ┆ Love Story                      ┆ 44164      │
│ …            ┆ …                      ┆ …                               ┆ …          │
│ 46           ┆ Metric                 ┆ Stadium Love                    ┆ 5606       │
│ 47           ┆ Cat Power              ┆ Sea Of Love                     ┆ 5546       │
│ 48           ┆ Armin van Buuren       ┆ In and Out of Love              ┆ 5500       │
│ 49           ┆ Eric Church            ┆ Love Your Love The Most         ┆ 5495       │
│ 50           ┆ Bryan Ferry            ┆ Slave To Love (1999 Digital Re… ┆ 5420       │
└──────────────┴────────────────────────┴─────────────────────────────────┴────────────┘
50 Most played songs with "war" in the title:
shape: (50, 4)
┌──────────────┬─────────────────────────────────┬─────────────────────────────┬────────────┐
│ index_number ┆ artist                          ┆ title                       ┆ play_count │
│ ---          ┆ ---                             ┆ ---                         ┆ ---        │
│ u32          ┆ str                             ┆ str                         ┆ i32        │
╞══════════════╪═════════════════════════════════╪═════════════════════════════╪════════════╡
│ 1            ┆ John Mayer                      ┆ Heartbreak Warfare          ┆ 43331      │
│ 2            ┆ Guns N' Roses                   ┆ Civil War                   ┆ 11493      │
│ 3            ┆ Bohren & Der Club Of Gore       ┆ Schwarze Biene (Black Maja) ┆ 10970      │
│ 4            ┆ Rise Against                    ┆ Hero Of War                 ┆ 9061       │
│ 5            ┆ Coldplay                        ┆ Warning Sign                ┆ 7161       │
│ …            ┆ …                               ┆ …                           ┆ …          │
│ 46           ┆ Flobots featuring Tim McIlrath… ┆ White Flag Warrior          ┆ 1109       │
│ 47           ┆ The Offspring                   ┆ Jennifer Lost The War       ┆ 1105       │
│ 48           ┆ Nine Inch Nails                 ┆ The Downward Spiral         ┆ 1099       │
│ 49           ┆ Wilco                           ┆ War on war                  ┆ 1087       │
│ 50           ┆ Frightened Rabbit               ┆ My Backwards Walk           ┆ 1073       │
└──────────────┴─────────────────────────────────┴─────────────────────────────┴────────────┘

## Collaborative Recommendation System

In [10]:
cfr = CollaborativeFilteringRecommender(df)
cfr.prepare_matrices(use_vectorizer=False)

# random user and song ids for recommending songs
user_id = df['user_id'][np.random.randint(0, len(df))]
song_id = df['song_id'][np.random.randint(0, len(df))]

# getting the recommendations
for_user_ids, for_user = cfr.recommend_for_user(user_id)
for_song_ids, for_song = cfr.recommend_for_song(song_id)

print("Calculating the p@k...")
sample_size, k = 100, 10
for_user_pk = cfr.evaluate_user_model(sample_size=sample_size, k=k)
for_song_pk = cfr.evaluate_song_model(sample_size=sample_size, k=k)

print("\nPeople similar to you listening:")
print(for_user)
print(f"Average Precision@{k} (p@k): {for_user_pk*100:.2f}%")
print("\nPeople who listen to this track usually listen:")
print(for_song)
print(f"Average Precision@{k} (p@k): {for_song_pk*100:.2f}%")

print("\n---- END RESULTS ------------------------")
print(f"Users similarity recommendation system Average Precision@{k} (p@k): {for_user_pk*100:.2f}%")
print(f"Tracks similarity recommendation system Average Precision@{k} (p@k): {for_song_pk*100:.2f}%")

Calculating the p@k...

People similar to you listening:
shape: (10, 3)
┌──────────────┬────────────────────────┬─────────────────────────────────┐
│ index_number ┆ artist                 ┆ title                           │
│ ---          ┆ ---                    ┆ ---                             │
│ u32          ┆ str                    ┆ str                             │
╞══════════════╪════════════════════════╪═════════════════════════════════╡
│ 1            ┆ Linkin Park            ┆ Crawling (Album Version)        │
│ 2            ┆ Muse                   ┆ Uprising                        │
│ 3            ┆ Coldplay               ┆ The Scientist                   │
│ 4            ┆ Five Iron Frenzy       ┆ Canada                          │
│ 5            ┆ Taylor Swift           ┆ You Belong With Me              │
│ 6            ┆ Cage The Elephant      ┆ Ain't No Rest For The Wicked (… │
│ 7            ┆ Kings Of Leon          ┆ Revelry                         │
│ 8            ┆ Florence + The Machine ┆ Cosmic Love                     │
│ 9            ┆ Eminem / Nate Dogg     ┆ 'Till I Collapse                │
│ 10           ┆ The Black Keys         ┆ Tighten Up                      │
└──────────────┴────────────────────────┴─────────────────────────────────┘
Average Precision@10 (p@k): 14.70%

People who listen to this track usually listen:
shape: (10, 3)
┌──────────────┬──────────────────────────┬─────────────────────────────────┐
│ index_number ┆ artist                   ┆ title                           │
│ ---          ┆ ---                      ┆ ---                             │
│ u32          ┆ str                      ┆ str                             │
╞══════════════╪══════════════════════════╪═════════════════════════════════╡
│ 1            ┆ My Chemical Romance      ┆ The Jetset Life Is Gonna Kill … │
│ 2            ┆ Khia                     ┆ My Neck_ My Back                │
│ 3            ┆ Paramore                 ┆ Whoa (Album Version)            │
│ 4            ┆ CCCP - Fedeli Alla Linea ┆ Aghia Sophia (2008 Digital Rem… │
│ 5            ┆ All Time Low             ┆ Umbrella                        │
│ 6            ┆ Yucatán Agogó            ┆ resispunk                       │
│ 7            ┆ Forever The Sickest Kids ┆ Uh Huh                          │
│ 8            ┆ Tomas Bodin              ┆ Back To The African Garden      │
│ 9            ┆ Justin Timberlake        ┆ What Goes Around...Comes Aroun… │
│ 10           ┆ Ana Cañas                ┆ Coração Vagabundo               │
└──────────────┴──────────────────────────┴─────────────────────────────────┘
Average Precision@10 (p@k): 7.60%

---- END RESULTS ------------------------
Users similarity recommendation system Average Precision@10 (p@k): 14.70%
Tracks similarity recommendation system Average Precision@10 (p@k): 7.60%